branch-defaults:
  main:
    environment: nodejs-env
    group_suffix: null
global:
  application_name: wind-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
